import styled from "styled-components";

interface PropsPattern {
  className?: string;
}

export default function Pattern({ className }: PropsPattern) {
  return (
    <StyledWrapper className={className}>
      <div className="jp-matrix">
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span> <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
        <span>マ</span>
        <span>ミ</span>
        <span>ム</span>
        <span>メ</span>
        <span>モ</span>
        <span>ヤ</span>
        <span>ユ</span>
        <span>ヨ</span>
        <span>ラ</span>
        <span>リ</span>
        <span>ル</span>
        <span>レ</span>
        <span>ロ</span>
        <span>ワ</span>
        <span>ヲ</span>
        <span>ン</span>
        <span>ガ</span>
        <span>ギ</span>
        <span>グ</span>
        <span>ゲ</span>
        <span>ゴ</span>
        <span>ザ</span>
        <span>ジ</span>
        <span>ズ</span>
        <span>ゼ</span>
        <span>ゾ</span>
        <span>ダ</span>
        <span>ヂ</span>
        <span>ヅ</span>
        <span>デ</span>
        <span>ド</span>
        <span>バ</span>
        <span>ビ</span>
        <span>ブ</span>
        <span>ベ</span>
        <span>ボ</span>
        <span>パ</span>
        <span>ピ</span>
        <span>プ</span>
        <span>ペ</span>
        <span>ポ</span>
        <span>ア</span>
        <span>イ</span>
        <span>ウ</span>
        <span>エ</span>
        <span>オ</span>
        <span>カ</span>
        <span>キ</span>
        <span>ク</span>
        <span>ケ</span>
        <span>コ</span>
        <span>サ</span>
        <span>シ</span>
        <span>ス</span>
        <span>セ</span>
        <span>ソ</span>
        <span>タ</span>
        <span>チ</span>
        <span>ツ</span>
        <span>テ</span>
        <span>ト</span>
        <span>ナ</span>
        <span>ニ</span>
        <span>ヌ</span>
        <span>ネ</span>
        <span>ノ</span>
        <span>ハ</span>
        <span>ヒ</span>
        <span>フ</span>
        <span>ヘ</span>
        <span>ホ</span>
      </div>
    </StyledWrapper>
  );
}

const StyledWrapper = styled.div`
  .jp-matrix {
    background-color: #05050a;

    width: 100%;
    height: 100%;
    overflow: hidden;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(40px, 1fr));
    grid-auto-rows: 40px;
    min-width: 100vw;
    min-height: 100vh;
    font-size: 32px;
    color: rgba(0, 150, 255, 0.4);
    font-family: "Courier New", Courier, monospace;
    justify-content: center;
    align-content: center;
  }

  .jp-matrix > span {
    text-align: center;
    text-shadow: 0 0 5px rgba(0, 150, 255, 0.5);
    user-select: none;
    transition:
      color 0.5s,
      text-shadow 0.5s;
    line-height: 1;
  }

  .jp-matrix > span:nth-child(19n + 2) {
    animation: smooth-pulse 3.5s ease-in-out infinite 0.2s;
  }
  .jp-matrix > span:nth-child(29n + 1) {
    animation: smooth-pulse 4.1s ease-in-out infinite 0.7s;
  }
  .jp-matrix > span:nth-child(11n) {
    color: rgba(100, 200, 255, 0.7);
    animation: smooth-pulse 2.9s ease-in-out infinite 1.1s;
  }
  .jp-matrix > span:nth-child(37n + 10) {
    animation: smooth-pulse 5.3s ease-in-out infinite 1.5s;
  }
  .jp-matrix > span:nth-child(41n + 1) {
    animation: smooth-pulse 3.9s ease-in-out infinite 0.4s;
  }
  .jp-matrix > span:nth-child(17n + 9) {
    animation: smooth-pulse 2.8s ease-in-out infinite 0.9s;
  }
  .jp-matrix > span:nth-child(23n + 18) {
    animation: smooth-pulse 4.3s ease-in-out infinite 1.3s;
  }
  .jp-matrix > span:nth-child(31n + 4) {
    animation: smooth-pulse 5.6s ease-in-out infinite 0.1s;
  }
  .jp-matrix > span:nth-child(43n + 20) {
    animation: smooth-pulse 3.6s ease-in-out infinite 1.8s;
  }
  .jp-matrix > span:nth-child(13n + 6) {
    animation: smooth-pulse 3.2s ease-in-out infinite 1.2s;
  }
  .jp-matrix > span:nth-child(53n + 5) {
    animation: smooth-pulse 4.9s ease-in-out infinite 0.5s;
  }
  .jp-matrix > span:nth-child(47n + 15) {
    animation: smooth-pulse 5.9s ease-in-out infinite 1s;
  }

  @keyframes smooth-pulse {
    0%,
    100% {
      color: rgba(0, 150, 255, 0.4);
      text-shadow: 0 0 5px rgba(0, 150, 255, 0.5);
    }
    30% {
      color: rgb(196, 163, 90, 0.5);
      text-shadow:
        0 0 10px rgb(196, 163, 90, 0.5),
        0 0 15px rgb(196, 163, 90, 0.5);
    }
    50% {
      color: rgba(196, 163, 90, 1);
      text-shadow:
        0 0 10px rgba(196, 163, 90, 1),
        0 0 15px rgba(196, 163, 90, 1);
    }
    70% {
      color: #ffffff;
      text-shadow:
        0 0 10px #fff,
        0 0 15px #fff,
        0 0 20px #fff;
    }
  }
`;
